Remove pygtk import
sugarlabs/cardsort pull request #7
Opened 2018-04-30 14:30 UTC by chimosky

2018-04-30 21:09 UTC, quozl commented
Are you sure about removing the `import os.path` from `card.py`?  There's a reference to `os.path` in that file.

Have you tested for PyGObject warnings?

2018-05-01 13:30 UTC, chimosky commented
I didn't notice i removed it earlier, added now. Tested for PyGObject warnings.

2018-05-02 00:35 UTC, quozl commented
Thanks.  Reviewed following the [guide for reviewers](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#guide-for-reviewers).

Was thinking of merging some of what you've done, but this would force you to rebase, so I'll pause to await your opinion.  You're still using your own _master_ branch; we [recommend against that](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#contributing).

Review comments;

* [ ] because the PyGObject warning happens on first import in a process, only one _gi.require_version_ is needed; in the main program file, the other calls are not necessary,
* [ ] you have changed the license of `sprites.py`, but (a) it isn't necessary to change it, (b) you aren't the author, and (c) the same file is in AEIOU, Abacus, Cookie Search, Fraction Bounce, I Can Read, Portfolio, Story, Turtle Blocks and others; it will look odd to have just one relicensed file; if license of this file is not changed, then _license_ in `activity.info` would then be "_MIT;GPLv3_",
* [ ] in `toolbar_utils.py`, my guess is that @i5o was claiming copyright for the GTK+ 3 port, so their line needs a "_Copyright (C)_" prefix,
* [ ] in all lines with "_Copyright (c)_" they should have a space before "_Copyright_", and the "_(c)_" should be uppercase "_(C)_",
* [ ] `setup.py` probably does not need a license, as it is trivial, but if it does has a license it should have copyright consistent with where it was likely copied from, and above all it must have a copyright line before the license, otherwise the license is ineffective.

Fixes https://github.com/sugarlabs/gmail-activity/issues/25.

2018-05-02 13:56 UTC, chimosky commented
Changes made
- [x] because the PyGObject warning happens on first import in a process, only one gi.require_version is needed; in the main program file, the other calls are not necessary,
- [x] you have changed the license of `sprites.py`, but (a) it isn't necessary to change it, (b) you aren't the author, and (c) the same file is in AEIOU, Abacus, Cookie Search, Fraction Bounce, I Can Read, Portfolio, Story, Turtle Blocks and others; it will look odd to have just one relicensed file; if license of this file is not changed, then license in `activity.info` would then be "MIT;GPLv3", ***license reverted***
- [x] in `toolbar_utils.py`, my guess is that @i5o was claiming copyright for the GTK+ 3 port, so their line needs a "Copyright (C)" prefix,
- [x] in all lines with "Copyright (c)" they should have a space before "Copyright", and the "(c)" should be uppercase "(C)",
- [x] `setup.py` probably does not need a license, as it is trivial, but if it does has a license it should have copyright consistent with where it was likely copied from, and above all it must have a copyright line before the license, otherwise the license is ineffective.
> You're still using your own master branch;

I actually use another branch and merge into my master branch once I'm done.

2018-05-04 13:40 UTC, chimosky commented
@quozl, kindly review.

2018-05-07 03:15 UTC, quozl requested changes
Thanks, good progress, but some backward steps.

2018-05-07 03:15 UTC, quozl commented on card.py
> +gi.require_version('Gtk', '3.0')
import and require_version not needed here, because it is already done for the process in CardSortActivity.py

2018-05-07 03:15 UTC, quozl commented on card.py
> +from gi.repository import Gtk, Gdk, GObject, GdkPixbuf
```
card.py:23:1: F401 'gi.repository.Gtk' imported but unused
card.py:23:1: F401 'gi.repository.GObject' imported but unused
card.py:23:1: F401 'gi.repository.Gdk' imported but unused
```

2018-05-07 03:15 UTC, quozl commented on card.py
> +
```
card.py:27:1: E302 expected 2 blank lines, found 1
```

2018-05-07 03:15 UTC, quozl commented on cardsort.py
> +gi.require_version('Gtk', '3.0')
import and require_version not needed here, because it is already done for the process in CardSortActivity.py

2018-05-07 03:15 UTC, quozl commented on cardsort.py
>  from gi.repository import Gdk, Gtk, GdkPixbuf, GObject
```
cardsort.py:24:1: F401 'gi.repository.GdkPixbuf' imported but unused
cardsort.py:24:1: F401 'gi.repository.GObject' imported but unused
```

2018-05-07 03:15 UTC, quozl commented on setup.py
> +
you added a blank line here.

2018-05-07 03:15 UTC, quozl commented on sprites.py
> +#Copyright (C) 2008-11 Walter Bender
would look more consistent with the other files if a space was placed after the "#" character

2018-05-07 03:15 UTC, quozl commented on toolbar_utils.py
> +gi.require_version('Gtk', '3.0')
import and require_version not needed here, because it is already done for the process in CardSortActivity.py

2018-05-07 03:15 UTC, quozl commented on window.py
> +gi.require_version('Gtk', '3.0')
import and require_version not needed here, because it is already done for the process in CardSortActivity.py

2018-05-07 03:15 UTC, quozl commented on window.py
> +GRID_CELL_SIZE = style.GRID_CELL_SIZE
rather than move this variable, it may be best to get rid of it and change the reference later from GRID_CELL_SIZE to style.GRID_CELL_SIZE.

2018-05-07 03:15 UTC, quozl commented on sprites.py
> +#Copyright (C) 2008-11 Walter Bender
sprites.py generates a PyGIWarning about PangoCairo; you didn't test?

2018-05-07 15:22 UTC, chimosky commented
Changes made.

2018-05-08 00:40 UTC, merged